[project]
name = "comfyui-rn-external-interface"
description = "RunNode external interface nodes for ComfyUI"
version = "1.19.0"

[tool.comfy]
PublisherId = "SF-Runnode"
DisplayName = "RunNode External Interface"
Icon = ""
